version: '2.2'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_ENABLE_TLS: Enable
    ports:
      - 5050:80
      - 443:443
    volumes:
      - /certs/fond.local.crt:/certs/server.cert
      - /certs/fond.local.key:/certs/server.key
      - pgadmin-data:/var/lib/pgadmin
      - /tmp/servers.json:/pgadmin4/servers.json
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:
